(*
 Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.12 2009/12/21 13:36:40 liutkuviene Exp
 ISO TC184/SC4/WG12 N6858 - ISO/TS 10303-1514 Advanced boundary representation - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N5273
*)

SCHEMA Advanced_boundary_representation_mim;

USE FROM Topologically_bounded_surface_mim; --ISO/TS 10303-1511:2004
USE FROM Solid_model_mim;
USE FROM aic_advanced_brep; --ISO/TS 10303-514

END_SCHEMA;

