(*
 Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.21 2012/10/11 05:49:06 liutkuviene Exp
 ISO TC184/SC4/WG12 N7871 - ISO/TS 10303-1346 Numeric function - EXPRESS MIM
 Supersedes ISO TC184/SC4/WG12 N7227 
*)

SCHEMA Numeric_function_mim;

USE FROM Elementary_function_mim;

USE FROM Expression_mim;

USE FROM iso13584_expressions_schema(
	int_value_function,
	length_function,	
	odd_function,	
	value_function);
	
END_SCHEMA;
