(*
   Part1000: $Id: $
 STEPmod.CVS.Id: mim.exp,v 1.3 2012/10/11 05:49:04 liutkuviene Exp
   ISO TC184/SC4/WG12 N7931 - ISO/CD-TS - 10303-1812 Product and manufacturing annotation presentation - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N7368
*)
(* UNDER DEVELOPMENT *)
SCHEMA Product_and_manufacturing_annotation_presentation_mim;

USE FROM Product_and_manufacturing_information_with_nominal_3d_models_mim;

END_SCHEMA;
